config/routes.rb
Rails.application.routes.draw do
 
  root to: 'visitors#index'

  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'

    resources :sold_properties do 
      collection do 
        post 'import'
        get 'sample'
        delete 'remove'
      end
    end
    resources :admins
    resources :suburbs
    resources :intros
    resources :outros
    resources :templates
    resources :users, except: [:new, :create] do
      member do
        get 'contacts'
        get 'intros'
        post 'intros_save'
        get 'outros'
        post 'outros_save'
        get 'templates'
        post 'templates_save'
        get 'resend_password'
        post 'import_contacts'
        get 'import_contacts'
        post 'import'
      end
      collection do 
        get 'sample'
      end
    end
  end

  namespace :api do
    scope module: 'v1' do
      resources :agents, only: [] do
        collection do
          post 'profile'
          post 'subscription'
        end
      end
      resources :contacts, only: [:index, :create,:edit,:update,:destroy] do
        collection do 
          post :add_contacts_by_email
        end
        resources :properties, only: [:index, :create, :edit, :update, :destroy]
      end
      resources :messages, only: [:index, :update,:show]
      resources :intros, only: [:index] do 
        collection do 
          put :select_intros
        end
      end
      resources :outros, only: [:index] do 
        collection do 
          put :select_outros
        end
      end
      resources :templates, only: [:index]
      resources :sold_properties,only: [:index] do         
      end
      get 'sold_properties/contacts', :to => "sold_properties#contacts" 
    end
  end


  devise_for :users, controllers: {
    confirmations: 'authentications/confirmations',
    passwords: 'authentications/passwords',
    sessions: 'authentications/sessions'
  }

  devise_for :agents,controllers: {
    registrations: 'authentications/registrations',
    sessions: 'authentications/sessions',
    passwords: 'authentications/passwords'
  }
end

app/models/intro.rb
class Intro < ActiveRecord::Base

	# has_and_belongs_to_many :users

	has_many :intros_users
	has_many :users,:through => :intros_users

	validates :message, presence: true

	def as_json(options = {})
	{
		id: id,
		message: message,
		user_id: options[:user_id]
	}
	end
end

app/models/user.rb
class User < ActiveRecord::Base
   extend Enumerize

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_secure_token :authentication_token
  has_many :contacts
  # has_and_belongs_to_many :intros
  has_many :intros_users, -> { where admin: true }
  has_many :intros, :through => :intros_users

  has_many :intros_users_user, -> { where admin: false }, class_name: 'IntrosUser'
  has_many :intros_admin_false, :through => :intros_users_user,:source => :intro #, class_name: 'Intro'


  has_many :outros_users, -> { where admin: true }
  has_many :outros, :through => :outros_users

  has_many :outros_users_user, -> { where admin: false }, class_name: 'OutrosUser'
  has_many :outros_admin_false, :through => :outros_users_user,:source => :outro #, class_name: 'Intro'


  enumerize :subscription, in: {
    "0-40 Contacts" => 40,
    "au.com.propertysmsapp.41_81" => 81, 
    "au.com.propertysmsapp.81_120" => 120,
    "au.com.propertysmsapp.121_160" => 160,
    "au.com.propertysmsapp.161_200" => 200,
    "au.com.propertysmsapp.201_500" => 500,
    "au.com.propertysmsapp.501" => 501}

  # has_many :outros_users
  # has_many :outros,:through => :outros_users

  # has_and_belongs_to_many :outros
  has_and_belongs_to_many :templates

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :mobile_number, presence: true

  def full_name
     "#{first_name} #{last_name}"
  end

  def as_json(options = {})
    if options[:subscription]
      {
        email: email,
        subscription: subscription,
        subscription_expired_at: subscription_expired_at,
        contacts_count: self.contacts.count
      }
    else
      {
        id: id,
        email: email,
        first_name: first_name,
        last_name: last_name,
        company: company,
        mobile_number: mobile_number,
        authentication_token: authentication_token,
        created_at: created_at,
        contacts_count: self.contacts.count,
        terms_accepted: terms_accepted,
        subscription: subscription,
        subscription_expired_at: subscription_expired_at
      }
    end
  end

  def self.import_contacts(params)

    user = User.find(params[:id])
    user_contact = user.contacts
    contact_hash = []
    
    xlsx = Roo::Spreadsheet.open(params[:file].path).sheet(0) 
    header = xlsx.row(1)

    (2..xlsx.last_row).each do |i|
      row = Hash[[header, xlsx.row(i)].transpose]
      contact_hash << row
    end
    contact_hash
    # CSV.foreach(params[:file].path, headers: true) do |row|
    #   unless row.to_hash.blank?
    #     contact_hash << row.to_hash
    #   end
    # end
    # contact_hash
  end

  def self.import(params)
    user = User.find(params[:id])
    previous_maximum_id = Property.maximum('id') || 1
    user_contact = Contact.unscoped.where(:user_id => user.id)
    contact_ids =  params[:contact_ids].map(&:to_i)
    
    xlsx = Roo::Spreadsheet.open(params[:file]).sheet(0)
    header = xlsx.row(1)
    
    sleep_count = 0

    (2..xlsx.last_row).each do |i|
      row = Hash[[header, xlsx.row(i)].transpose]

      sleep_count = sleep_count+1 if sleep_count == 0

      if contact_ids.include?(i)
        contact_hash = row.to_hash

        contact_hash["Mobile Number"] =  (contact_hash["Mobile Number"].is_a? Numeric) ? contact_hash["Mobile Number"].to_i.to_s : contact_hash["Mobile Number"]  
        contact_hash["Unit Number1"] = (contact_hash["Unit Number1"].is_a? Numeric) ? contact_hash["Unit Number1"].to_i.to_s : contact_hash["Unit Number1"] 
        contact_hash["House Number1"] = (contact_hash["House Number1"].is_a? Numeric) ? contact_hash["House Number1"].to_i.to_s : contact_hash["House Number1"] 
        contact_hash["Street1"] = (contact_hash["Street1"].is_a? Numeric) ? contact_hash["Street1"].to_i.to_s : contact_hash["Street1"] 
        contact_hash["State1"] = (contact_hash["State1"].is_a? Numeric) ? contact_hash["State1"].to_i.to_s :  contact_hash["State1"] 
        contact_hash["Post Code1"] = (contact_hash["Post Code1"].is_a? Numeric) ?  contact_hash["Post Code1"].to_i.to_s : contact_hash["Post Code1"]
        contact_hash["Unit Number2"] = (contact_hash["Unit Number2"].is_a? Numeric) ? contact_hash["Unit Number2"].to_i.to_s : contact_hash["Unit Number2"] 
        contact_hash["House Number2"] = (contact_hash["House Number2"].is_a? Numeric) ? contact_hash["House Number2"].to_i.to_s : contact_hash["House Number2"] 
        contact_hash["Street2"] = (contact_hash["Street2"].is_a? Numeric) ? contact_hash["Street2"] : contact_hash["Street2"]
        contact_hash["State2"] = (contact_hash["State2"].is_a? Numeric) ? contact_hash["State2"].to_i.to_s : contact_hash["State2"]
        contact_hash["Post Code2"] = (contact_hash["Post Code2"].is_a? Numeric) ? contact_hash["Post Code2"].to_i.to_s : contact_hash["Post Code2"]
        contact_hash["Unit Number3"] = (contact_hash["Unit Number3"].is_a? Numeric) ? contact_hash["Unit Number3"].to_i.to_s : contact_hash["Unit Number3"] 
        contact_hash["House Number3"] = (contact_hash["House Number3"].is_a? Numeric) ? contact_hash["House Number3"].to_i.to_s : contact_hash["House Number3"] 
        contact_hash["Street3"] = (contact_hash["Street3"].is_a? Numeric) ?  contact_hash["Street3"].to_i.to_s :  contact_hash["Street3"] 
        contact_hash["State3"] = (contact_hash["State3"].is_a? Numeric) ? contact_hash["State3"].to_i.to_s : contact_hash["State3"] 
        contact_hash["Post Code3"] = (contact_hash["Post Code3"].is_a? Numeric) ? contact_hash["Post Code3"].to_i.to_s : contact_hash["Post Code3"]

        if contact_hash["Investment Property1"] == "TRUE" or contact_hash["Investment Property1"] == "true" or contact_hash["Investment Property1"] == 1.0 or contact_hash["Investment Property1"] == 1 or contact_hash["Investment Property1"] == true
          contact_hash["Investment Property1"] = true
        end

        if contact_hash["Investment Property1"] == "FALSE" or contact_hash["Investment Property1"] == "false" or contact_hash["Investment Property1"] == 0.0 or contact_hash["Investment Property1"] == 0 or contact_hash["Investment Property1"] == false
          contact_hash["Investment Property1"] = false
        end

        if contact_hash["Investment Property2"] == "TRUE" or contact_hash["Investment Property2"] == "true" or contact_hash["Investment Property2"] == 1.0 or contact_hash["Investment Property2"] == 1 or contact_hash["Investment Property2"] == true
          contact_hash["Investment Property2"] = true
        end

        if contact_hash["Investment Property2"] == "FALSE" or contact_hash["Investment Property2"] == "false" or contact_hash["Investment Property2"] == 0.0 or contact_hash["Investment Property2"] == 0 or contact_hash["Investment Property2"] == false
          contact_hash["Investment Property2"] = false
        end

        if contact_hash["Investment Property3"] == "TRUE" or contact_hash["Investment Property3"] == "true" or contact_hash["Investment Property3"] == 1.0 or contact_hash["Investment Property3"] == 1 or contact_hash["Investment Property3"] == true
          contact_hash["Investment Property3"] = true
        end

        if contact_hash["Investment Property3"] == "FALSE" or contact_hash["Investment Property3"] == "false" or contact_hash["Investment Property3"] == 0.0 or contact_hash["Investment Property3"] == 0 or contact_hash["Investment Property3"] == false
          contact_hash["Investment Property3"] = false
        end


        contact = user_contact.where(:mobile_number => contact_hash["Mobile Number"]).first

        if contact and contact.deleted?
          contact.update_column(:deleted,false)
        # else
        #   contact = user_contact.where(:mobile_number => contact_hash["mobile_number"]).first
        end
        if contact.blank? 
          contact = user.contacts.build(:first_name => contact_hash["First Name"] , :last_name => contact_hash["Last Name"],:mobile_number => contact_hash["Mobile Number"],:partner_first_name => contact_hash["Partner First Name"],:partner_last_name => contact_hash["Partner Last Name"])
          contact_true = contact.save
        end
        if contact || contact_true 
          
          if contact_hash["Unit Number1"].present? or  contact_hash["House Number1"].present? or contact_hash["Street1"].present? or contact_hash["Suburb1"].present? or contact_hash["State1"].present? or contact_hash["Post Code1"].present?
            p = contact.properties.find_or_initialize_by(:unit_number => contact_hash["Unit Number1"],:house_number => contact_hash["House Number1"],
              :street=> contact_hash["Street1"],
              :suburb=> contact_hash["Suburb1"],:state => contact_hash["State1"],:postcode => contact_hash["Post Code1"])
            if p.new_record?
              p.investment_property = contact_hash["Investment Property1"]
              sleep_count +=1
            end
            p.save
          end

          if contact_hash["Unit Number2"].present? or  contact_hash["House Number2"].present? or contact_hash["Street2"].present? or contact_hash["Suburb2"].present? or contact_hash["State2"].present? or contact_hash["Post Code2"].present?

            p = contact.properties.find_or_initialize_by(:unit_number => contact_hash["Unit Number2"],:house_number => contact_hash["House Number2"],
              :street=> contact_hash["Street2"],
              :suburb=> contact_hash["Suburb2"],:state => contact_hash["State2"],:postcode => contact_hash["Post Code2"])
            if p.new_record?
              p.investment_property = contact_hash["Investment Property2"]
              sleep_count +=1
            end
            p.save
          end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  layout 'admin'

  before_filter :authenticate_admin!
  before_action :set_user, only: [
    :show, :edit, :update, :destroy,
    :contacts,
    :intros, :intros_save,
    :outros, :outros_save,
    :templates, :templates_save,
    :resend_password
  ]

  # GET /users
  # GET /users.json
  def index
    if params[:s].nil?
      @users = User.order(:first_name).paginate(:page => params[:page], :per_page => 20)
    else
      @users = User.where("first_name LIKE '%#{params[:s]}%' OR last_name LIKE '%#{params[:s]}%' OR company LIKE '%#{params[:s]}%' OR email LIKE '%#{params[:s]}%'").order(:first_name).paginate(:page => params[:page], :per_page => 20)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        @user.update_column(:email, params[:user][:email])
        format.html { redirect_to admins_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_users_path, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # GET /users/1/contacts
  # GET /users/1/contacts.json
  def contacts
  end

  def import_contacts

      @file = params[:file].path if params[:file]
      @contact_array = [] unless @contact_array
      if request.post? 
        if (params[:file].content_type == "application/vnd.ms-excel" || params[:file].content_type == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet") and validate_header?(@file)
          @contact_array =  User.import_contacts(params) 
        else
          flash[:notice] = "Not a valid format or file is empty"
        end
      end
  end

  def import
    get_prev_max_imported_id = User.import(params)
    Property.create_coordinate(get_prev_max_imported_id)
    # MessageJob.new.async.perform(for_contact_property_coordinate: get_prev_max_imported_id)
    redirect_to admins_users_url ,:notice => "Successfully saved"
  end

  def sample
    respond_to do |format| 
       format.xlsx {render xlsx: 'sample',filename: "sample.xlsx"}
    end
    # respond_to do |format| 
    #   format.xlsx do
    #       response.headers['Content-Type'] = 'text/xlsx'
    #       response.headers['Content-Disposition'] = 'attachment; filename=sample.xlsx'    
    #       render "sample.xlsx.erb"
    #   end
    # end
  end

  # GET /users/1/intros
  # GET /users/1/intros.json
  def intros
    @intros = Intro.all
  end

  # POST /users/1/intros_save
  # POST /users/1/intros_save.json
  def intros_save
    @user.intros.destroy_all
    if !params[:intro].nil? && !params[:intro].blank?
      params[:intro].each do |intro_id|
        intro = Intro.find(intro_id)
        @user.intros << intro
      end
    end
    redirect_to intros_admins_user_path, notice: 'Intros was successfully updated.'
  end

  # GET /users/1/outros
  # GET /users/1/outros.json
  def outros
    @outros = Outro.all
  end

  # POST /users/1/outros_save
  # POST /users/1/outros_save.json
  def outros_save
    @user.outros.destroy_all
    if !params[:outro].nil? && !params[:outro].blank?
      params[:outro].each do |outro_id|
        outro = Outro.find(outro_id)
        @user.outros << outro
      end
    end
    redirect_to outros_admins_user_path, notice: 'Outros was successfully updated.'
  end

  # GET /users/1/templates
  # GET /users/1/templates.json
  def templates
    @templates = Template.all
  end

  # POST /users/1/templates_save
  # POST /users/1/templates_save.json
  def templates_save
    @user.templates.destroy_all
    if !params[:template].nil? && !params[:template].blank?
      params[:template].each do |template_id|
        template = Template.find(template_id)
        @user.templates << template
      end
    end
    redirect_to templates_admins_user_path, notice: 'Templates was successfully updated.'
  end

  def resend_password
    @user.send_reset_password_instructions
    flash[:notice] =  "Password instructions has successfully been sent to user's email address."
    redirect_to admins_users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :company, :mobile_number, :email)
    end

    def validate_header?(params)
      User.valid_header?(params)
    end
end

app/views/admins/users/_select_users.html.erb
<div class="col-md-4">
  <div class="operator">
    <h2>SELECT USERS</h2>
    <span>You can assign all or specific user(s).</span>
    <span class="all-s">
      <%= f.check_box :all_users, { id: 'all_users'} %>
      <label for="all_users"><span>Select All</span></label>
    </span>
    <%= select_tag 'users', options_from_collection_for_select(@users, 'id', 'full_name', user_ids), {:multiple => true} %>
  </div>
</div>
<script>
  $(document).on('ready page:load', function () {
    select_users();

    modify_options();
    
    $('#all_users').on('change', function() {
      modify_options();
      $("option:selected").prop("selected", false);
    });
    
    function modify_options() {
      if ($("#all_users").is(":checked")) {
            $('.operator option').css("box-shadow","0 0 0 14px #fff inset");
             $("#token-container").tokenfield("destroy");
             $("#token-container").val("");
             $("#token-container")
             .tokenfield();
             $('#users').attr('disabled', 'disabled');
         }
         else {
            $("#users option").removeAttr("style");
            $('#users').removeAttr('disabled');
         }
    }
  });
</script>

app/views/admins/users/_user.html.erb
<td><%= count %></td>
<td><%= user.first_name %> <%= user.last_name %></td>
<td><%= user.company %></td>
<td><%= user.mobile_number %></td>
<td><%= user.email %></td>
<td><%= link_to 'View', ['admins', user] %></td>
<td><%= link_to 'Edit', edit_admins_user_path(user) %></td>
<td><%= link_to 'Delete', ['admins', user], method: :delete, data: { confirm: "Are you sure?" } %></td>
<td><%= link_to 'Contacts', contacts_admins_user_path(user) %></td>
<td><%= link_to 'Import', import_contacts_admins_user_path(user) %></td>
<td><%= link_to 'Intros', intros_admins_user_path(user) %></td>
<td><%= link_to 'Template', templates_admins_user_path(user) %></td>
<td><%= link_to 'Outros', outros_admins_user_path(user) %></td>
<td><%= link_to 'Reset Password', resend_password_admins_user_path(user) %></td>

app/views/admins/users/_user_info.html.erb
<table class="table table-condensed">
  <tbody>
    <tr>
      <td width="20%">Name:</td>
      <td><%= @user.first_name %> <%= @user.last_name%></td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>Company name:</td>
      <td><%= @user.company %></td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>Email:</td>
      <td><%= @user.email %><b</td>
    </tr>
  </tbody>
</table>
<br /><br />

app/views/admins/users/import_contacts.html.erb
<div class="row">
<div class="col-sm-12">
  <ol class="breadcrumb ">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Import contacts</li>
  </ol>
  </div>
</div><!--/.row-->

<% if @contact_array.blank?%>
	<div class="row">
		<div class="col-sm-12">
			<%= form_tag import_contacts_admins_user_path, multipart: true ,class: "form-horizontal bottom-indent" do %>
			
			<div class="form-group">
				<div class="col-sm-5">
					<%= file_field_tag :file , accept: 'text/xlsx',:class=>"form-control",:required => true%>
					<%= hidden_field_tag :id , params[:id] %>
				</div>
				<div class="col-sm-4">
					It only support xlsx and xls files. Please match the header given as in sample file before importing.There should only be one sheet in excel file.
					<%= link_to "Download Sample", sample_admins_users_path(:format => "xlsx") ,:class => ""%>
				</div>
			</div>

				<% if @contact_array.blank?%>
					<%= link_to raw('<i class="fa fa-chevron-left "></i>Back'), admins_users_path, class: 'btn btn-danger top-indent' %>
				<% end %>

				<%= submit_tag "Import" ,class: "btn btn-primary top-indent"%>
			<% end %>
		</div>
	</div>
<% end %>

<% unless @contact_array.blank?%>
	<div class="row">
		<div class="col-sm-12">
	   <%= form_tag(import_admins_user_path, method: "post") do %>
	   	<div style="overflow-x:auto;">
			<table class="table table-striped table-bordered bottom-indent">
			<thead>
				<th><input type="checkbox" id="checkAll" /></th>
				<th>First Name</th>
				<th>Last Name</th>
				<th> Mobile Number</th>
				<th>Partner First Name</th>
				<th>Partner Last Name</th>
				<th> Unit Number1</th>
				<th> House Number1 </th>
				<th>Street1</th>
				<th> Suburb1 </th>
				<th> State1</th>
				<th>Post Code1</th>
				<th>Investment Property1</th>
				<th> Unit Number2</th>
				<th> House Number2 </th>
				<th>Street2</th>
				<th> Suburb2 </th>
				<th> State2</th>
				<th>Post Code2</th>
				<th>Investment Property2</th>
				<th> Unit Number3</th>
				<th> House Number3 </th>
				<th>Street3</th>
				<th> Suburb3 </th>
				<th> State3</th>
				<th>Post Code3</th>
				<th>Investment Property3</th>
			</thead>
			<tbody id="checkbox-container">
				<% @contact_array.each_with_index do |c, index| %>
					<%
					 if c["Investment Property1"] == "TRUE" or c["Investment Property1"] == "true" or c["Investment Property1"] == 1.0 or c["Investment Property1"] == 1
					 	c["Investment Property1"] = true
					 end

					 if c["Investment Property1"] == "FALSE" or c["Investment Property1"] == "false" or c["Investment Property1"] == 0.0 or c["Investment Property1"] == 0
					 	c["Investment Property1"] = false
					 end

					 if c["Investment Property2"] == "TRUE" or c["Investment Property2"] == "true" or c["Investment Property2"] == 1.0 or c["Investment Property2"] == 1
					 	c["Investment Property2"] = true
					 end

					 if c["Investment Property2"] == "FALSE" or c["Investment Property2"] == "false" or c["Investment Property2"] == 0.0 or c["Investment Property2"] == 0
					 	c["Investment Property2"] = false
					 end

					 if c["Investment Property3"] == "TRUE" or c["Investment Property3"] == "true" or c["Investment Property3"] == 1.0 or c["Investment Property3"] == 1
					 	c["Investment Property3"] = true
					 end

					 if c["Investment Property3"] == "FALSE" or c["Investment Property3"] == "false" or c["Investment Property3"] == 0.0 or c["Investment Property3"] == 0
					 	c["Investment Property3"] = false
					 end

					 	%>
					<tr>
						<td><%= check_box_tag 'contact_ids[]', index+2 %>
							<%= hidden_field_tag :file,@file%>
						</td>
						<td><%= c["First Name"]%></td>
						<td><%= c["Last Name"]%></td>
						<td><%= (c["Mobile Number"].is_a? Numeric) ? c["Mobile Number"].to_i.to_s : c["Mobile Number"]  %></td>
						<td><%= c["Partner First Name"]%></td>
						<td><%= c["Partner Last Name"]%></td>
						<td><%= (c["Unit Number1"].is_a? Numeric) ? c["Unit Number1"].to_i.to_s : c["Unit Number1"] %></td>
						<td><%= (c["House Number1"].is_a? Numeric) ? c["House Number1"].to_i.to_s : c["House Number1"] %></td>
						<td><%= (c["Street1"].is_a? Numeric) ? c["Street1"].to_i.to_s : c["Street1"] %></td>
						<td><%= c["Suburb1"]%></td>
						<td><%= (c["State1"].is_a? Numeric) ? c["State1"].to_i.to_s :  c["State1"] %></td>
						<td><%= (c["Post Code1"].is_a? Numeric) ?  c["Post Code1"].to_i.to_s : c["Post Code1"]%></td>
						<td><%= c["Investment Property1"]%></td>
						<td><%= (c["Unit Number2"].is_a? Numeric) ? c["Unit Number2"].to_i.to_s : c["Unit Number2"] %></td>
						<td><%= (c["House Number2"].is_a? Numeric) ? c["House Number2"].to_i.to_s : c["House Number2"] %></td>
						<td><%= (c["Street2"].is_a? Numeric) ? c["Street2"].to_i.to_s : c["Street2"] %></td>
						<td><%= c["Suburb2"]%></td>
						<td><%= (c["State2"].is_a? Numeric) ? c["State2"].to_i.to_s : c["State2"]%></td>
						<td><%= (c["Post Code2"].is_a? Numeric) ? c["Post Code2"].to_i.to_s : c["Post Code2"]%></td>
						<td><%= c["Investment Property2"]%></td>
						<td><%= (c["Unit Number3"].is_a? Numeric) ? c["Unit Number3"].to_i.to_s : c["Unit Number3"] %></td>
						<td><%= (c["House Number3"].is_a? Numeric) ? c["House Number3"].to_i.to_s : c["House Number3"] %></td>
						<td><%= (c["Street3"].is_a? Numeric) ?  c["Street3"].to_i.to_s :  c["Street3"] %></td>
						<td><%= c["Suburb3"] %></td>
						<td><%= (c["State3"].is_a? Numeric) ? c["State3"].to_i.to_s : c["State3"] %></td>
						<td><%= (c["Post Code3"].is_a? Numeric) ? c["Post Code3"].to_i.to_s : c["Post Code3"]%></td>
						<td><%= c["Investment Property3"]%></td>
					</tr>
				<% end %>
			</tbody>
		</table> 
	</div>
		<%= submit_tag("Save" ,class: "btn btn-success top-indent")%>
		<%= link_to raw('<i class="fa fa-chevron-left "></i>Back'), request.headers["HTTP_REFERER"], class: 'btn btn-danger top-indent' %>
		<% end %>
		</div>
	</div>
<% end %>

app/views/admins/users/intros.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active"><%= @user.first_name %> <%= @user.last_name%>: Intros</li>
  </ol>
</div>
<div class="row">
  <div class="user-info column">
    <%= render partial: 'user_info' %>
    <%= form_tag(intros_save_admins_user_path) do %>
      <table class="table table-responsive">
        <% if @intros.count == 0 %>
          <tr><td>No Record Found.</td></tr>
        <% else %>
          <% intros_ids = @user.intros.pluck(:intro_id) %>
          <thead>
            <tr>
              <th>S.NO.</th>
              <th>Select All</th>
              <th><input type="checkbox" id="checkAll" /></th>
              <th>Intros</th>
            </tr>
          </thead>
          <tbody id="checkbox-container">
            <% counter = 1 %>
            <% @intros.each do |intro| %>
              <tr>
                <td><%= counter %></td>
                <td>
                  <% if intro.all_users?%>
                    Yes
                  <%else%>
                    No
                  <% end %>
                </td>
                <td>
                <% unless intro.all_users?%>
                  <input type="checkbox" name="intro[]" value="<%= intro.id %>" <%= 'checked="checked"' if intros_ids.include?(intro.id) %> />
                <% end %>
                </td>
                <td><%= intro.message %></td>
              </tr>
              <% counter += 1 %>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="3">
                <div class="actions">
                  <%= submit_tag 'Save', :class => 'btn btn-success' %>
                </div>
              </td>
            </tr>
          </tfoot>
        <% end %>
      </table>
    <% end %>
    <%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_users_path, class: 'btn btn-danger'  %>
  </div>
</div>