config/routes.rb
Rails.application.routes.draw do
 
  root to: 'visitors#index'

  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'

    resources :sold_properties do 
      collection do 
        post 'import'
        get 'sample'
        delete 'remove'
      end
    end
    resources :admins
    resources :suburbs
    resources :intros
    resources :outros
    resources :templates
    resources :users, except: [:new, :create] do
      member do
        get 'contacts'
        get 'intros'
        post 'intros_save'
        get 'outros'
        post 'outros_save'
        get 'templates'
        post 'templates_save'
        get 'resend_password'
        post 'import_contacts'
        get 'import_contacts'
        post 'import'
      end
      collection do 
        get 'sample'
      end
    end
  end

  namespace :api do
    scope module: 'v1' do
      resources :agents, only: [] do
        collection do
          post 'profile'
          post 'subscription'
        end
      end
      resources :contacts, only: [:index, :create,:edit,:update,:destroy] do
        collection do 
          post :add_contacts_by_email
        end
        resources :properties, only: [:index, :create, :edit, :update, :destroy]
      end
      resources :messages, only: [:index, :update,:show]
      resources :intros, only: [:index] do 
        collection do 
          put :select_intros
        end
      end
      resources :outros, only: [:index] do 
        collection do 
          put :select_outros
        end
      end
      resources :templates, only: [:index]
      resources :sold_properties,only: [:index] do         
      end
      get 'sold_properties/contacts', :to => "sold_properties#contacts" 
    end
  end


  devise_for :users, controllers: {
    confirmations: 'authentications/confirmations',
    passwords: 'authentications/passwords',
    sessions: 'authentications/sessions'
  }

  devise_for :agents,controllers: {
    registrations: 'authentications/registrations',
    sessions: 'authentications/sessions',
    passwords: 'authentications/passwords'
  }
end

app/models/outro.rb
class Outro < ActiveRecord::Base

	# has_and_belongs_to_many :users
	has_many :outros_users
	has_many :users,:through => :outros_users

	validates :message, presence: true

	def as_json(options = {})
	{
		id: id,
		message: message,
		user_id: options[:user_id]
	}
	end
end

app/controllers/admins/outros_controller.rb
class Admins::OutrosController < ApplicationController
  layout 'admin'

  before_filter :authenticate_admin!
  before_action :set_outro, only: [:show, :edit, :update, :destroy]

  # GET /outros
  # GET /outros.json
  def index
    if params[:s].nil?
      @outros = Outro.paginate(:page => params[:page], :per_page => 20)
    else
      @outros = Outro.where("message LIKE '%#{params[:s]}%'").paginate(:page => params[:page], :per_page => 20)
    end
  end

  # GET /outros/1
  # GET /outros/1.json
  def show
  end

  # GET /outros
  def new
     @outro = Outro.new
     @users = User.order(:first_name)
  end

  # GET /outros/1/edit
  def edit
     @users = User.order(:first_name)
  end

  # PATCH/POST /outros/1
  # PATCH/POST /outros/1.json
  def create
    @outro = Outro.new(outro_params)
     @users = User.order(:first_name)

    respond_to do |format|
      if @outro.save
        save_selected_users

        format.html { redirect_to admins_outros_path, notice: 'Outro was successfully created.' }
        format.json { render :show, status: :ok, location: @outro }
      else
        format.html { render :edit }
        format.json { render json: @outro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outros/1
  # PATCH/PUT /outros/1.json
  def update
     @users = User.order(:first_name)
    respond_to do |format|
      if @outro.update(outro_params)

        save_selected_users
        format.html { redirect_to admins_outros_path, notice: 'Outro was successfully updated.' }
        format.json { render :show, status: :ok, location: @outro }
      else
        format.html { render :edit }
        format.json { render json: @outro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outros/1
  # DELETE /outros/1.json
  def destroy
    @outro.destroy
    respond_to do |format|
      format.html { redirect_to admins_outros_url, notice: 'Outro was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def save_selected_users
      @outro.users.destroy_all
      if !params[:users].nil? && !params[:users].blank?
        params[:users].each do |user_id|
          user = User.find(user_id)
          @outro.users << user
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_outro
      @outro = Outro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outro_params
      params.require(:outro).permit(:message, :all_users)
    end
end

app/controllers/api/v1/outros_controller.rb
class Api::V1::OutrosController < ApplicationController
	before_filter :authenticate_agent_from_token!

def index
  
  # outros = Outro.where("outros_users.user_id = ? ",current_user.id).joins("INNER JOIN outros_users on outros.id = outros_users.outro_id ") | Outro.where("all_users =?",true)
  outros = current_user.outros | Outro.where("all_users =?",true)
  user_selected = current_user.outros_admin_false.pluck(:outro_id).uniq

  outros = outros.sort_by {|obj| obj.id}

  respond_to do |format|
    format.json { render :json => outros.uniq.as_json({:user_id => current_user.id}).push(user_selected)}
  end
end

def select_outros	
	respond_to do |format|
		if params[:admin] and params[:outro_id]
			user_outros = current_user.outros_users_user.where(:outro_id => params[:outro_id]).first
			if params[:admin] == "true"
				if !user_outros.nil?
					user_outros.destroy
				end
			else
				if user_outros.nil?
					current_user.outros_users_user.create(outro_id: params[:outro_id], admin: false)
				end
			end
				format.json { render :json => {:success => true}}
			else
				format.json { render :json => {:error => true},:status =>  :unprocessable_entity}
			end
	end	
end

end

app/views/admins/outros/_form.html.erb
<div class="row">
  <%= form_for [:admins, @outro] do |f| %>
    <div class="col-md-8">
      <% if @outro.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@outro.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
          <% @outro.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field token-holder">
        <%= f.label :User_name %>
        <div id="token-container" class="token-holder"></div>
      </div>
      <div class="field mess">
        <%= f.label :Use_these_in_message %>
        <div class="holder">
          <button type="button" value="[ Contact First Name ]" data-input="outro_message" class="in_message">Contact First Name</button>
          <button type="button" value="[ Contact Last Name ]" data-input="outro_message" class="in_message">Contact Last Name</button>
          <button type="button" value="[ Partner First Name ]" data-input="outro_message" class="in_message">Partner First Name</button>
          <button type="button" value="[ Partner Last Name ]" data-input="outro_message" class="in_message">Partner Last Name</button>

          <button type="button" value="[ User First Name ]" data-input="outro_message" class="in_message">User First Name</button>
          <button type="button" value="[ User Last Name ]" data-input="outro_message" class="in_message">User Last Name </button>
          <button type="button" value="[ Company Name ]" data-input="outro_message" class="in_message">Company Name</button>

          <!-- <button type="button" value="[ CONTACT NAME ]" data-input="outro_message" class="in_message">Contact Name</button>
          <button type="button" value="[ USER NAME ]" data-input="outro_message" class="in_message">User Name</button>
          <button type="button" value="[ COMPANY NAME ]" data-input="outro_message" class="in_message">Company Name</button> -->
        </div>
      </div>
      <div class="field mess">
        <%= f.label :Outros_message %>
        <%= f.text_area :message, :rows => 5, :cols => 100 %>
      </div>
      <div class="field">
        <%= f.label :Character_count %>
        <%= text_field_tag :character_count, '', disabled: true %>
      </div>

      <div class="actions">
        <%= f.submit 'Save', :class => 'btn btn-success' %>
      </div>
    </div>
    <%= render partial: 'admins/users/select_users', locals: {:f => f, :user_ids => @outro.users.pluck(:user_id) } %>
  <% end %>
</div>

app/views/admins/outros/_outro.html.erb
<td><%= counter %></td>
<td><%= outro.message %></td>
<td><%= link_to 'View', ['admins', outro] %></td>
<td><%= link_to 'Edit', edit_admins_outro_path(outro) %></td>
<td><%= link_to 'Delete', ['admins', outro], method: :delete, data: { confirm: "Are you sure?" } %></td>

app/views/admins/outros/edit.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Edit Outro</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to 'Show', ['admins', @outro], class: 'btn btn-success' %>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_outros_path, class: 'btn btn-danger' %>

app/views/admins/outros/index.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Outros</li>
  </ol>
</div><!--/.row-->

<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <%= link_to raw('<i class="fa fa-plus">&nbsp;</i> Add'), new_admins_outro_path, class: 'btn btn-success' %>
    </div>
    <div class="pull-right">
      <form>
        <div class="dataTables_filter" id="datatable_filter">
          <label>
            <input type="text" name="s" maxlength="100"  value="<%= params[:s] %>" aria-controls="datatable" class="form-control" placeholder=" ">
          </label>
          <button class="search-btn pull-right">
              <input type="submit" class="btn btn-primary" value="Submit">
              <i class="fa fa-search"></i>
          </button>
        </div>
      </form>
    </div>
    <div class="clearfix"></div>
  </div>
</div> 
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @outros.count == 0 %>
          <table class="table table-responsive">
            <tr><td>No Record Found.</td></tr>
          </table>
        <% else %>
          <table data-toggle="table" data-show-refresh="false" data-show-toggle="false" data-show-columns="false" data-search="true" data-select-item-name="toolbar1" data-pagination="false" data-sort-name="name" data-sort-order="desc" class="table table-hover">
            <thead>
              <tr>
                  <th>S.NO.</th>
                  <th>Outros</th>
                  <th colspan="3">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% counter = 1 %>
                <% @outros.each do |outro| %>
                  <tr>
                    <%= render outro, :counter => counter %>
                  </tr>
                  <% counter += 1 %>
                <% end %>
              </tr>
            </tbody>
          </table>
          <div class="fixed-table-pagination">
            <div class="pull-right pagination">
              <%= will_paginate @outros, renderer: BootstrapPagination::Rails %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!--/.row-->

app/views/admins/outros/new.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Add Outro</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_outros_path, class: 'btn btn-danger' %>

app/views/admins/outros/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Outros View page</li>
  </ol>
</div><!--/.row-->
<div class="row">
  <div class="user-info column">
    <table class="table table-responsive">
      <tr>
        <td width="20%">Outro Id:</td>
        <td><%= @outro.id %></td>
      </tr>
      <tr>
        <td>Message:</td>
        <td><%= @outro.message %></td>
      </tr>
    </table>

    <%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_outros_path, class: 'btn btn-danger'  %>
  </div>
</div>