config/routes.rb
Rails.application.routes.draw do
 
  root to: 'visitors#index'

  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'

    resources :sold_properties do 
      collection do 
        post 'import'
        get 'sample'
        delete 'remove'
      end
    end
    resources :admins
    resources :suburbs
    resources :intros
    resources :outros
    resources :templates
    resources :users, except: [:new, :create] do
      member do
        get 'contacts'
        get 'intros'
        post 'intros_save'
        get 'outros'
        post 'outros_save'
        get 'templates'
        post 'templates_save'
        get 'resend_password'
        post 'import_contacts'
        get 'import_contacts'
        post 'import'
      end
      collection do 
        get 'sample'
      end
    end
  end

  namespace :api do
    scope module: 'v1' do
      resources :agents, only: [] do
        collection do
          post 'profile'
          post 'subscription'
        end
      end
      resources :contacts, only: [:index, :create,:edit,:update,:destroy] do
        collection do 
          post :add_contacts_by_email
        end
        resources :properties, only: [:index, :create, :edit, :update, :destroy]
      end
      resources :messages, only: [:index, :update,:show]
      resources :intros, only: [:index] do 
        collection do 
          put :select_intros
        end
      end
      resources :outros, only: [:index] do 
        collection do 
          put :select_outros
        end
      end
      resources :templates, only: [:index]
      resources :sold_properties,only: [:index] do         
      end
      get 'sold_properties/contacts', :to => "sold_properties#contacts" 
    end
  end


  devise_for :users, controllers: {
    confirmations: 'authentications/confirmations',
    passwords: 'authentications/passwords',
    sessions: 'authentications/sessions'
  }

  devise_for :agents,controllers: {
    registrations: 'authentications/registrations',
    sessions: 'authentications/sessions',
    passwords: 'authentications/passwords'
  }
end

app/views/admins/admins/_admin.html.erb
<td><%= counter %></td>
<td><%= admin.email %></td>
<td><%= admin.encrypted_password%></td>
<td><%= admin.status%></td>
<td><%= link_to 'View', ['admins', admin] %></td>
<td><%= link_to 'Edit', edit_admins_admin_path(admin) %></td>
<td><%= link_to 'Delete', ['admins', admin], method: :delete, data: { confirm: "Are you sure?" } %></td>

app/views/admins/admins/_form.html.erb
<div class="row">
  <%= form_for [:admins,@admin] , class: "form-horizontal " do |f| %>
    <div class="col-md-8">
      <% if @admin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
          <% @admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field token-holder">
        <%= f.label :email,class: "control-label" %>
        <%= f.text_field :email ,class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password ,class: "control-label"%>
        <%= f.password_field :password ,class: "form-control"%>
      </div>
      <div class="field form-inline">
        <%= f.label :status ,class: "control-label"%>
        <%= f.select :status, options_for_select(Admin.statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @admin.status), {} , class: "form-control" %>
      </div>


      <div class="actions">
        <%= f.submit 'Save', :class => 'btn btn-success' %>
      </div>
    </div>

  <% end %>
</div>

app/views/admins/admins/destroy.html.erb
<h1>Admins#destroy</h1>
<p>Find me in app/views/admins/destroy.html.erb</p>

app/views/admins/admins/edit.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Edit Admins</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to 'Show', ['admins', @admin], class: 'btn btn-success' %>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_admins_path, class: 'btn btn-danger' %>

app/views/admins/admins/index.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Admins</li>
  </ol>
</div><!--/.row-->

<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <%= link_to raw('<i class="fa fa-plus">&nbsp;</i> Add'), new_admins_admin_path, class: 'btn btn-success' %>
    </div>
    <div class="pull-right">
      <form>
        <div class="dataTables_filter" id="datatable_filter">
          <label>
            <input type="text" name="s" maxlength="100"  value="<%= params[:s] %>" aria-controls="datatable" class="form-control" placeholder=" ">
          </label>
          <button class="search-btn pull-right">
              <input type="submit" class="btn btn-primary" value="Submit">
              <i class="fa fa-search"></i>
          </button>
        </div>
      </form>
    </div>
    <div class="clearfix"></div>
  </div>
</div> 
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @admins.count == 0 %>
          <table class="table table-responsive">
            <tr><td>No Record Found.</td></tr>
          </table>
        <% else %>
          <table data-toggle="table" data-show-refresh="false" data-show-toggle="false" data-show-columns="false" data-search="true" data-select-item-name="toolbar1" data-pagination="false" data-sort-name="name" data-sort-order="desc" class="table table-hover">
            <thead>
              <tr>
                  <th>S.NO.</th>
                  <th>Email</th>
                  <th>Password</th>
                  <th>Active</th>
                  <th colspan="3">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% counter = 1 %>
                <% @admins.each do |admin| %>
                  <tr>
                    <%= render admin, :counter => counter %>
                  </tr>
                  <% counter += 1 %>
                <% end %>
              </tr>
            </tbody>
          </table>
          <div class="fixed-table-pagination">
            <div class="pull-right pagination">
              <%= will_paginate @admins, renderer: BootstrapPagination::Rails %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!--/.row-->

app/views/admins/admins/new.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Add Admin</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_admins_path, class: 'btn btn-danger' %>

app/views/admins/admins/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Admin View page</li>
  </ol>
</div><!--/.row-->
<div class="row">
  <div class="user-info column">
    <table class="table table-responsive">
      <tr>
        <td width="20%">Admin Id:</td>
        <td><%= @admin.id %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= @admin.email %></td>
      </tr>

      <tr>
        <td>Password:</td>
        <td><%= @admin.encrypted_password %></td>
      </tr>
    </table>

    <%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_admins_path, class: 'btn btn-danger'  %>
  </div>
</div>

app/views/admins/admins/update.html.erb
<h1>Admins#update</h1>
<p>Find me in app/views/admins/update.html.erb</p>