config/routes.rb
Rails.application.routes.draw do
 
  root to: 'visitors#index'

  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'

    resources :sold_properties do 
      collection do 
        post 'import'
        get 'sample'
        delete 'remove'
      end
    end
    resources :admins
    resources :suburbs
    resources :intros
    resources :outros
    resources :templates
    resources :users, except: [:new, :create] do
      member do
        get 'contacts'
        get 'intros'
        post 'intros_save'
        get 'outros'
        post 'outros_save'
        get 'templates'
        post 'templates_save'
        get 'resend_password'
        post 'import_contacts'
        get 'import_contacts'
        post 'import'
      end
      collection do 
        get 'sample'
      end
    end
  end

  namespace :api do
    scope module: 'v1' do
      resources :agents, only: [] do
        collection do
          post 'profile'
          post 'subscription'
        end
      end
      resources :contacts, only: [:index, :create,:edit,:update,:destroy] do
        collection do 
          post :add_contacts_by_email
        end
        resources :properties, only: [:index, :create, :edit, :update, :destroy]
      end
      resources :messages, only: [:index, :update,:show]
      resources :intros, only: [:index] do 
        collection do 
          put :select_intros
        end
      end
      resources :outros, only: [:index] do 
        collection do 
          put :select_outros
        end
      end
      resources :templates, only: [:index]
      resources :sold_properties,only: [:index] do         
      end
      get 'sold_properties/contacts', :to => "sold_properties#contacts" 
    end
  end


  devise_for :users, controllers: {
    confirmations: 'authentications/confirmations',
    passwords: 'authentications/passwords',
    sessions: 'authentications/sessions'
  }

  devise_for :agents,controllers: {
    registrations: 'authentications/registrations',
    sessions: 'authentications/sessions',
    passwords: 'authentications/passwords'
  }
end

app/models/intro.rb
class Intro < ActiveRecord::Base

	# has_and_belongs_to_many :users

	has_many :intros_users
	has_many :users,:through => :intros_users

	validates :message, presence: true

	def as_json(options = {})
	{
		id: id,
		message: message,
		user_id: options[:user_id]
	}
	end
end

app/views/admins/templates/_form.html.erb
<div class="row">
  <%= form_for [:admins, @template] do |f| %>
    <div class="col-md-8">
      <% if @template.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@template.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @template.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field token-holder">
        <%= f.label :User_name %>
        <div id="token-container" class="token-holder"></div>
      </div>
      <div class="field">
        <%= f.label :Template_group %>
        <%= f.select "group", options_for_select(['A','B','C', 'D', 'E'], :selected => f.object.group) %>
      </div>
      <div class="field mess">
        <%= f.label :Use_these_in_message %>
        <div class="holder">
          <button type="button" value="[ LISTING ADDRESS ]" data-input="template_message" class="in_message">Listing Address</button>
          <button type="button" value="[ FULL LISTING ADDRESS ]" data-input="template_message" class="in_message">Full Listing Address</button>
          <button type="button" value="[ DISTANCE ]" data-input="template_message" class="in_message">Distance</button>
          <button type="button" value="[ $XXXXXX ]" data-input="template_message" class="in_message">$XXXXXX</button>
          <button type="button" value="[ BxB ]" data-input="template_message" class="in_message">BxB</button>
          <button type="button" value="[ STREET ]" data-input="template_message" class="in_message">STREET</button>
          <button type="button" value="[ STREET IF INVESTMENT ]" data-input="template_message" class="in_message">Street If Investment</button>
        </div>
      </div>
      <div class="field mess">
        <%= f.label :Template_message %>
        <%= f.text_area :message, :rows => 5, :cols => 100 %>
      </div>
      <div class="field">
        <%= f.label :Character_count %>
        <%= text_field_tag :character_count, '', disabled: true %>
      </div>

      <div class="actions">
        <%= f.submit 'Save', :class => 'btn btn-success' %>
      </div>
    </div>
    <%= render partial: 'admins/users/select_users', locals: {:f => f, :user_ids => @template.users.pluck(:user_id) } %>
  <% end %>
</div>

app/views/admins/templates/_template.html.erb
<td><%= counter %></td>
<td><%= template.message %></td>
<td><%= template.group %></td>
<td><%= link_to 'View', ['admins', template] %></td>
<td><%= link_to 'Edit', edit_admins_template_path(template) %></td>
<td><%= link_to 'Delete', ['admins', template], method: :delete, data: { confirm: "Are you sure?" } %></td>

app/views/admins/templates/edit.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Edit Template</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to 'Show', ['admins', @template], class: 'btn btn-success' %>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_templates_path, class: 'btn btn-danger' %>

app/views/admins/templates/index.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Templates</li>
  </ol>
</div><!--/.row-->

<div class="row">
  <div class="col-sm-12">
    <form id="template_list">
      <div class="col-md-2">
        <%= link_to raw('<i class="fa fa-plus">&nbsp;</i> Add'), new_admins_template_path, class: 'btn btn-success' %>
      </div>
      <div class="col-md-2">
        <%= select_tag "g", options_for_select(['All','A','B','C', 'D', 'E'], :selected => params[:g]), id: 'template_group' %>
      </div>
      <div class="pull-right">
        <div class="dataTables_filter" id="datatable_filter">
          <label>
            <input type="text" name="s" maxlength="100"  value="<%= params[:s] %>" aria-controls="datatable" class="form-control" placeholder=" ">
          </label>
          <button class="search-btn pull-right">
              <input type="submit" class="btn btn-primary" value="Submit">
              <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
      <div class="clearfix"></div>
    </form>
  </div>
</div> 
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @templates.count == 0 %>
          <table class="table table-responsive">
            <tr><td>No Record Found.</td></tr>
          </table>
        <% else %>
          <table data-toggle="table" data-show-refresh="false" data-show-toggle="false" data-show-columns="false" data-search="true" data-select-item-name="toolbar1" data-pagination="false" data-sort-name="name" data-sort-order="desc" class="table table-hover">
            <thead>
              <tr>
                  <th>S.NO.</th>
                  <th>Template</th>
                  <th>Template Group</th>
                  <th colspan="3">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% counter = 1 %>
                <% @templates.each do |template| %>
                  <tr>
                    <%= render template, :counter => counter %>
                  </tr>
                  <% counter += 1 %>
                <% end %>
              </tr>
            </tbody>
          </table>
          <div class="fixed-table-pagination">
            <div class="pull-right pagination">
              <%= will_paginate @outros, renderer: BootstrapPagination::Rails %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!--/.row-->

app/views/admins/templates/new.html.erb
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
	  <li class="active">Add Template</li>
	</ol>
</div><!--/.row-->
<%= render 'form' %>
<br>
<%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_templates_path, class: 'btn btn-danger' %>

app/views/admins/templates/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
    <li class="active">Templates View page</li>
  </ol>
</div><!--/.row-->
<div class="row">
  <div class="user-info column">
    <table class="table table-responsive">
      <tr>
        <td width="20%">Template Id:</td>
        <td><%= @template.id %></td>
      </tr>
      <tr>
        <td>Message:</td>
        <td><%= @template.message %></td>
      </tr>
    </table>

    <%= link_to raw('<i class="fa fa-chevron-left"></i>Back'), admins_templates_path, class: 'btn btn-danger'  %>
  </div>
</div>